version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cueu0jrtq21c73epcppg-a/mysql_app
      - SPRING_DATASOURCE_USERNAME=mysql_app_user
      - SPRING_DATASOURCE_PASSWORD=MNc6OqlmuWkVcXh6wCxxeL6s0krf9cPI
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mysql_app_user
      POSTGRES_PASSWORD: MNc6OqlmuWkVcXh6wCxxeL6s0krf9cPI
      POSTGRES_DB: mysql_app
    ports:
      - "5432:5432"
